name: "version release"
permissions:
  contents: write
on:
  workflow_dispatch: # allows manual triggering
    inputs:
      level:
        description: 'release version level'
        required: true
        default: 'alpha'
        type: choice
        options:
        - alpha
        - beta
        - rc
        - minor
        - major
jobs:
  call-workflow-passing-data:
    uses: M-Adoo/rclog/.github/workflows/release-version.yml@feat/release-workflow
    with:
      level: ${{ github.event.inputs.level }}
      ref: ${{ github.ref }}
    
      
