name: "Dispatch foregin workflows"

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.RELEASE_VERSION }}
        script: |-
          await github.rest.actions.createWorkflowDispatch({
              owner: 'RibirX',
              repo: 'ribir-website',
              workflow_id: 'sync-docs.yml',
              ref: 'auto-deploy-ci',
              inputs: {
                version: "${{ github.ref }}"
              },
          }).catch(error => error).then(response => {
            core.debug(response);
            if (response.status !== 204) {
              core.setFailed(`create workflow_dispatch received status code ${response.status}`);
            }
          });
    