name: Update Changelog
on:
  merge_group:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace PR id in Changelog
        run: |
          pr=$(echo ${{ github.event.merge_group.head_ref }} | grep -Eo "queue/main/pr-[0-9]+" | cut -d '-' -f2)
          sed -i "s/#pr/#${pr}/g" ./CHANGELOG.md
      - name: Commit and push changes
        run: |
          if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "No changes to commit."
            exit 0
          fi
          git config --global user.name "RChangelog[bot]"
          git config --global user.email 155627257+RChangelog[bot]@users.noreply.github.com
          git add .
          git commit --amend --no-edit
          git push